In [6]:
import numpy as np
from numpy import *

In [7]:
a = np.array([1,23,4,5,656,4543])
a

array([   1,   23,    4,    5,  656, 4543])

In [8]:
b = np.array([1,2,3,4,5,6,7,8])
b

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
print(a.ndim,a.shape)

1 (6,)


In [11]:
random.rand(3,5)

array([[0.22394856, 0.11528741, 0.21749018, 0.40501106, 0.9762051 ],
       [0.3557398 , 0.81205825, 0.83173504, 0.88396   , 0.66582553],
       [0.36430759, 0.66845634, 0.53572464, 0.93387751, 0.89578666]])

In [14]:
# matrix

randMat = mat(random.rand(3,3))
randMat

matrix([[0.48399514, 0.53339951, 0.17278706],
        [0.79881305, 0.78305159, 0.05556234],
        [0.23707375, 0.03570232, 0.13251402]])

In [15]:
invMat = randMat.I
invMat

matrix([[-3.72511861,  2.36115692,  3.86721998],
        [ 3.39206454, -0.84810682, -4.06735864],
        [ 5.75051036, -3.99572014,  1.72357477]])

In [17]:
identity = randMat * invMat
identity


matrix([[ 1.00000000e+00, -1.96100313e-16, -1.68139231e-16],
        [-2.30415539e-16,  1.00000000e+00, -1.28632056e-16],
        [-5.51704927e-17, -1.04687263e-16,  1.00000000e+00]])

In [22]:
# 2d array 
a = np.array([[1,2,3],
     [2,3,4]])
print(a.ndim)
print(a.shape)

2
(2, 3)


In [28]:
b = np.array([[1,2],[2,3]],dtype='int8')
b.dtype


dtype('int8')

In [34]:
aa = np.array(range(10,20),int)
aa = aa.reshape(2,5)
print(aa)

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [36]:
ab = aa.reshape(5,2)
print(ab)

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [37]:
a1 = np.array([[1,2],[2,4]])
a2 = np.array([[3,4],[5,6]])
np.concatenate((a1,a2))

array([[1, 2],
       [2, 4],
       [3, 4],
       [5, 6]])

In [38]:
np.concatenate((a1,a2),axis= 1)

array([[1, 2, 3, 4],
       [2, 4, 5, 6]])

In [41]:
# New axis method
abc = np.array([1,2,3,4,5])

print(abc,abc.ndim,abc.shape)

ab  = abc[:,np.newaxis]

print(ab,ab.ndim, ab.shape)

[1 2 3 4 5] 1 (5,)
[[1]
 [2]
 [3]
 [4]
 [5]] 2 (5, 1)


In [47]:
# creation of array with np.arange()
# np.arange(start,stop,step,dtype)

av = np.arange(10,25,2,dtype='int16')

In [49]:
av1 = av.reshape(2,4)
print(av1,av1.ndim,av1.shape)

[[10 12 14 16]
 [18 20 22 24]] 2 (2, 4)


In [50]:
# np.ones()
aone = np.ones((3,3),dtype=int)

In [51]:
aone

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [54]:
azero = np.zeros((3,3),dtype=int)

In [55]:
azero

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [59]:
# np.zeros_like()
# np.ones_like()

a = np.array([[1,2,3],[3,5,6],[4,6,3]],dtype=int)
print(a,'\n')
print(np.zeros_like(a),'\n')
print(np.ones_like(a))

[[1 2 3]
 [3 5 6]
 [4 6 3]] 

[[0 0 0]
 [0 0 0]
 [0 0 0]] 

[[1 1 1]
 [1 1 1]
 [1 1 1]]


# Manipulating Arrays Shapes

### np.ravel()
### np.flatten()
### np.transpose()
### np.resize()

In [61]:
# np.ravel() it is used convert n dimensional array to 1-dimensional array
a = np.array([[1,3,4],[2,4,5],[23,5,3]])
print(a,'\n')
r = a.ravel()
r

[[ 1  3  4]
 [ 2  4  5]
 [23  5  3]] 



array([ 1,  3,  4,  2,  4,  5, 23,  5,  3])

In [64]:
# np.flatten()  same as ravel() but continuously assigns novel memory where as ravel might return with a result of an array

a = np.array([[1,3,4],[2,4,5],[23,5,3]],dtype=int)

print(a.flatten())

[ 1  3  4  2  4  5 23  5  3]


In [65]:
# np.reshape()

a = np.array([[1,3,4],[2,4,5],[23,5,3],[23,4,24]])

a = a.reshape(3,4)

In [66]:
a

array([[ 1,  3,  4,  2],
       [ 4,  5, 23,  5],
       [ 3, 23,  4, 24]])

In [68]:
at = a.transpose()
at

array([[ 1,  4,  3],
       [ 3,  5, 23],
       [ 4, 23,  4],
       [ 2,  5, 24]])

# STACKING IN NUMPY

## Vertical Stacking
## Horizental Stacking
## Depth Stacking 
## Column_Stacking
## Row_Stacking

# Vertical Stacking 
##### In vertical stacking more than 2 matrices are stacked  vertically

In [72]:
a = np.array([[1,2],[3,5]])
b = np.array([[4,4],[43,65]])
print(a,'\n\n',b)

[[1 2]
 [3 5]] 

 [[ 4  4]
 [43 65]]


In [74]:
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  5],
       [ 4,  4],
       [43, 65]])

# Horizental Stacking
### In horizental stacking more than 2 matrices are stacked horizentally

In [75]:
a1 = np.array([[1,2],[3,4],[5,3]])
b1 = np.array([[1,34],[2,45],[42,5]])
print(a1,'\n\n',b1)

[[1 2]
 [3 4]
 [5 3]] 

 [[ 1 34]
 [ 2 45]
 [42  5]]


In [76]:
np.hstack((a1,b1))

array([[ 1,  2,  1, 34],
       [ 3,  4,  2, 45],
       [ 5,  3, 42,  5]])

# Depth Stacking 
### In depth stacking 2 or more matrices are combined in depth wise together by added diminsion

In [79]:
a12 = np.array([[1,34],[34,532]])
b12 = np.array([[21,32],[24,53]])
c12 = np.array([[223,42],[54,54]])
print(a12,'\n\n',b12,'\n\n',c12)

[[  1  34]
 [ 34 532]] 

 [[21 32]
 [24 53]] 

 [[223  42]
 [ 54  54]]


In [80]:
np.dstack((a12,b12,c12))

array([[[  1,  21, 223],
        [ 34,  32,  42]],

       [[ 34,  24,  54],
        [532,  53,  54]]])

# Row_stacking 


In [86]:
a = np.array(10*np.random.random((2,2)),dtype=int)
b = np.array(10*np.random.random((2,2)),dtype=int)
print(a,'\n\n',b)

[[6 4]
 [3 5]] 

 [[1 6]
 [1 3]]


In [89]:
np.row_stack((a,b))
np.vstack((a,b))
np.row_stack((a,b))==np.vstack((a,b))

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

# Column Stacking

In [96]:
a = np.array(10*np.random.random((3,3)),dtype=int)
b = np.array(10*np.random.random((3,3)),dtype=int)
print(a,'\n\n',b)

[[2 5 1]
 [2 8 7]
 [3 0 5]] 

 [[8 1 5]
 [3 1 8]
 [1 6 5]]


In [97]:
np.column_stack((a,b))

array([[2, 5, 1, 8, 1, 5],
       [2, 8, 7, 3, 1, 8],
       [3, 0, 5, 1, 6, 5]])

# Splitting Arrays
### Horizental Splitting
### Vertical Splitting
### Depth wise Splitting

---

In [101]:
a = np.array(10*np.random.random((3,3)),dtype=int)
b = np.array(10*np.random.random((3,3)),dtype=int) 
print(a,'\n\n',b)

[[2 8 5]
 [0 3 9]
 [1 5 5]] 

 [[0 0 0]
 [5 2 6]
 [9 0 7]]


In [104]:
hsplit(a,3)

[array([[2],
        [0],
        [1]]),
 array([[8],
        [3],
        [5]]),
 array([[5],
        [9],
        [5]])]

In [106]:
vsplit(b,3)

[array([[0, 0, 0]]), array([[5, 2, 6]]), array([[9, 0, 7]])]

In [108]:
dsplit(a,3)

ValueError: dsplit only works on arrays of 3 or more dimensions

# Statistics using NumPy
### mean(), median(), mode()
### corelation-coefficient() => corrcoef()
### Covarience() => cov()

In [119]:
a = np.array([1,34,52,5343,632,664,63])
a

array([   1,   34,   52, 5343,  632,  664,   63])

In [120]:
np.mean(a)

969.8571428571429

In [121]:
np.median(a)

63.0

In [122]:
np.mode(a)

AttributeError: module 'numpy' has no attribute 'mode'

In [123]:
np.corrcoef(a)

1.0

In [124]:
np.cov(a)

array(3801906.47619048)